FROM ubuntu:focal

ARG ROOT
ENV BUILD=debug

WORKDIR /app

# Install dependencies
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y git
RUN apt-get install -y python2
RUN apt-get install -y uuid-dev
RUN apt-get install -y libgomp1

# Build glib
RUN git clone https://github.com/qminer/qminer.git

# TODO: Remove commit checkout and fix glib compilation error
RUN cd qminer/src/glib && \
    git checkout a7aa7b8d843b6d75eca6f870c054bec9684a978a && \
    make ${BUILD} && \
    mv glib.a glib-${BUILD}.a

# Copy project files from host
COPY $ROOT .

# Build service
RUN make ${BUILD}
RUN mkdir -p bin
RUN mv ss2 bin

# Run service
EXPOSE 8096
CMD ["./bin/ss2", "-port:8096", "-fnUnicodeDef:src/UnicodeDef.bin", "-logfile:modelling.log"]
