version: '3.4'

services:
    api:
        # container_name: streamstory_api
        build:
            context: .
            dockerfile: ./services/api/Dockerfile.dev
            args:
                ROOT: ./services/api
        depends_on:
            - db
            - modelling
        volumes:
            - ./services/api:/app
            - /app/node_modules
            - /app/configs
            - /app/scripts
            - data:/app/data
        ports:
            - ${API_PORT:-3001}:8080
        links:
            - data
            - db
            - email
            - modelling
        environment:
            DB_NAME: streamstory
            DB_USER: root
            DB_PASSWORD: password

    client:
        # container_name: streamstory_client
        build:
            context: .
            dockerfile: ./services/client/Dockerfile.dev
            args:
                ROOT: ./services/client
        depends_on:
            - api
        volumes:
            - ./services/client:/app
            - /app/node_modules
            - /app/configs
            - /app/scripts
            - /app/src/config/i18n
        ports:
            - ${CLIENT_PORT:-3000}:3000
        links:
            - api
        environment:
            PORT: 3000
            REACT_APP_PROXY: http://api:8080

    data:
        # container_name: streamstory_data
        build:
            context: .
            dockerfile: ./services/data/Dockerfile.dev
            args:
                ROOT: ./services/data
        volumes:
            - ./services/data:/app
            - /app/node_modules
        ports:
            - ${DATA_PORT:-3002}:8081

    db:
        # container_name: streamstory_db
        # image: postgres:11.12
        build:
            context: .
            dockerfile: ./services/db/Dockerfile
            args:
                ROOT: ./services/db
        volumes:
            - ./services/db/data:/var/lib/postgresql/data
            - ./services/db/schema:/docker-entrypoint-initdb.d
            - ./services/db/upgrade:/upgrade
        ports:
            - ${DB_PORT:-5432}:5432
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: streamstory
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password

    email:
        # container_name: streamstory_email
        image: mailhog/mailhog
        ports:
            - ${EMAIL_CLIENT_PORT:-8025}:8025

    modelling:
        # container_name: streamstory_modelling
        build:
            context: .
            dockerfile: ./services/modelling/Dockerfile.dev
            args:
                ROOT: ./services/modelling
        volumes:
            - ./services/modelling:/app
            - /app/bin
            - /app/qminer
            - data:/app/data
        ports:
            - ${MODELLING_PORT:-8096}:8096

volumes:
    data:
