version: '3.4'

services:
    client:
        # container_name: streamstory_client
        build:
            context: ./services/client
            dockerfile: Dockerfile
        depends_on:
            - api
        links:
            - api
        ports:
            - 80:80
        restart: unless-stopped

    api:
        # container_name: streamstory_api
        build:
            context: ./services/api
            dockerfile: Dockerfile
        depends_on:
            - db
        links:
            - db
        # ports:
        #     - 8080:80
        restart: unless-stopped
        environment:
            HOST: ${HOST}
            SESSION_SECRET: ${SESSION_SECRET}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_PORT: ${EMAIL_PORT}
            EMAIL_USER: ${EMAIL_USER}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}

    db:
        # container_name: streamstory_db
        # image: postgres:11.12
        build:
            context: ./services/db
            dockerfile: Dockerfile
        volumes:
            - ./services/db/data:/var/lib/postgresql/data
            - ./services/db/schema:/docker-entrypoint-initdb.d
        # ports:
        #     - 5432:5432
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST:-db}
            POSTGRES_PORT: ${POSTGRES_PORT:-5432}
            POSTGRES_DB: ${POSTGRES_DB:-streamstory}
            POSTGRES_USER: ${POSTGRES_USER:-root}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
        restart: unless-stopped
