version: '3.4'

services:
    client:
        # container_name: streamstory_client
        build:
            context: ./services/client
            dockerfile: Dockerfile.dev
        depends_on:
            - api
        volumes:
            - ./services/client:/app
            - /app/node_modules
        ports:
            - ${PORT:-3000}:${PORT:-3000}
        links:
            - api
        environment:
            PORT: ${PORT:-3000}
            REACT_APP_PROXY: ${REACT_APP_PROXY:-http://api:3001}

    api:
        # container_name: streamstory_api
        build:
            context: ./services/api
            dockerfile: Dockerfile.dev
        depends_on:
            - modelling
            - db
        volumes:
            - ./services/api:/app
            - /app/node_modules
            - data:/app/data
        ports:
            - ${API_PORT:-3001}:${API_PORT:-3001}
        links:
            - modelling
            - db
            - email
        environment:
            API_PORT: ${API_PORT:-3001}
            HOST: ${HOST:-http://localhost:3000}
            SESSION_SECRET: ${SESSION_SECRET}
            EMAIL_HOST: ${EMAIL_HOST:-email}
            EMAIL_PORT: ${EMAIL_PORT:-1025}
            EMAIL_USER: ${EMAIL_USER:-user@email.com}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD:-password}

    modelling:
        # container_name: streamstory_modelling
        build:
            context: ./services/modelling
            dockerfile: Dockerfile.dev
            args:
                MODELLING_PORT: ${MODELLING_PORT}
        volumes:
            - ./services/modelling:/app
            - /app/bin
            - /app/qminer
            - data:/app/data
        ports:
            - ${MODELLING_PORT:-8096}:${MODELLING_PORT:-8096}

    db:
        # container_name: streamstory_db
        # image: postgres:11.12
        build:
            context: ./services/db
            dockerfile: Dockerfile
        volumes:
            - ./services/db/data:/var/lib/postgresql/data
            - ./services/db/schema:/docker-entrypoint-initdb.d
        ports:
            - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST:-db}
            POSTGRES_PORT: ${POSTGRES_PORT:-5432}
            POSTGRES_DB: ${POSTGRES_DB:-streamstory}
            POSTGRES_USER: ${POSTGRES_USER:-root}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

    email:
        # container_name: streamstory_email
        image: mailhog/mailhog
        ports:
            - ${EMAIL_PORT:-1025}:1025
            - ${EMAIL_CLIENT_PORT:-8025}:8025

volumes:
    data:
