FROM node:14.17.0-alpine3.11

EXPOSE 3001

ENV NODE_ENV=development

# RUN addgroup app && adduser -S -G app app
# USER app

WORKDIR /app
COPY ["package*.json", "./"]
RUN npm install
COPY . .

CMD ["npm", "run", "dev"]
