FROM node:14.17.0-alpine3.11

ENV NODE_ENV=development

# RUN addgroup app && adduser -S -G app app
# USER app

WORKDIR /app

# Install dependencies
COPY ["package*.json", "./"]
RUN npm install

# Copy project files from host
COPY . .

# Run service
EXPOSE 3001
CMD ["npm", "run", "dev"]
