FROM node:14.18.1-alpine3.14

ARG CONFIG
ARG CONFIG_NAME=${CONFIG:-development}
ARG ROOT
ENV NODE_ENV=development

WORKDIR /app

# Install dependencies
RUN apk add --no-cache gettext
RUN apk add --no-cache perl

COPY $ROOT/package*.json .
RUN npm install

# Copy project files from host
COPY $ROOT .

# Setup config
COPY ./scripts ./scripts
COPY ./configs/$CONFIG_NAME.json ./config.json
COPY .en[v] .

RUN source scripts/loadenv.sh .env && \
    format=$(perl -e 'print "\$$_" for grep /^[_a-zA-Z]\w*$/, keys %ENV') && \
    envsubst "$format" < config.json | tee _config.json && \
    node scripts/setupConfig.js api ./_config.json > config.json && \
    mkdir -p configs && \
    mv config.json configs && \
    rm _config.json

# Run service
EXPOSE 8080
CMD ["sh", "-c", "export CONFIG=$(cat configs/config.json); npm run dev"]
