FROM node:14.18.1-alpine3.14

ARG CONFIG=development
ARG CONFIG_NAME=${CONFIG:-development}
ARG ROOT
ENV NODE_ENV=development

WORKDIR /app

# Install dependencies
RUN apk add --no-cache gettext
RUN apk add --no-cache perl

COPY $ROOT/package*.json ./
RUN npm install

# Copy project files from host
COPY $ROOT .

# Setup config
COPY ./scripts ./scripts
COPY ./configs ./configs
COPY .en[v] .

RUN source scripts/loadenv.sh .env && \
    format=$(perl -e 'print "\$$_" for grep /^[_a-zA-Z]\w*$/, keys %ENV') && \
    envsubst "$format" < ./configs/$CONFIG_NAME/config.json | tee $CONFIG_NAME.json && \
    node scripts/setupConfig.js client ./$CONFIG_NAME.json > config.json && \
    mv config.json configs && \
    rm $CONFIG_NAME.json

# Run service
EXPOSE 3000
CMD ["sh", "-c", "export REACT_APP_CONFIG=$(cat configs/config.json); npm start"]
